
---
- hosts: all
  connection: local
  
  tasks:
     - ios_config:
          provider: "{{login_info}}" 
          lines:
            - mgcp call-agent 10.0.0.10
          before: "no mgcp call-agent 10.0.0.9"  
       
     - ios_config:
          save: yes
          provider: "{{login_info}}"
